"""empty message

Revision ID: 32555eec10ab
Revises: 557d7b13fe54
Create Date: 2021-06-23 20:06:53.897416

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '32555eec10ab'
down_revision = '557d7b13fe54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('phone', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'phone')
    # ### end Alembic commands ###
