"""empty message

Revision ID: 557d7b13fe54
Revises: ef2c2260d73c
Create Date: 2021-06-23 19:49:13.390149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '557d7b13fe54'
down_revision = 'ef2c2260d73c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'phone')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('phone', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
